name: test_ios
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cloud_firestore_web: ^3.6.2
  firebase_auth_web: ^5.5.3
  firebase_core_web: ^2.6.0
  firebase_messaging_web: ^3.5.3
  firebase_storage_web: ^3.6.4
  shared_preferences_web: ^2.2.0
  flutter_screenutil: ^5.7.0
  cloud_firestore: ^4.8.2
  image_picker: ^1.0.1
  firebase_storage: ^11.2.4
  firebase_auth: ^4.6.3
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.2.0
  #carousel_pro: ^1.0.0
  flare_flutter: ^3.0.2
  firebase_messaging: ^14.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/icon.png
    - assets/image/onBoarding1.png
    - assets/image/onBoarding2.png
    - assets/image/onBoarding3.png
    - assets/image/article1.jpg
    - assets/image/IlustrasiCart.png
    - assets/image/image_01.png
    - assets/image/image_02.png
    - assets/image/banner.png
    - assets/image/backgroundBanner.png
    - assets/image/logo.png
    - assets/image/news.png
    - assets/gif/event1.gif
    - assets/gif/event2.gif
    - assets/gif/event3.gif
    - assets/image/emptyProfilePicture.png
    - assets/image/cover.png
    - assets/icon/notification.png
    - assets/icon/creditAcount.png
    - assets/icon/fashion.png
    - assets/icon/chat.png
    - assets/icon/truck.png
    - assets/icon/setting.png
    - assets/icon/callcenter.png
    - assets/icon/aboutapp.png
    - assets/icon/otomotif.png
    - assets/icon/pc.png
    - assets/icon/sport.png
    - assets/icon/ticket.png
    - assets/icon/logout.png
    - assets/icon/calendar.png
    - assets/icon/bookmart.png
    - assets/icon/canada.png
    - assets/icon/editProfile.png
    - assets/icon/england.png
    - assets/icon/italia.png
    - assets/icon/paris.png
    - assets/icon/spanyol.png
    - assets/icon/thailand.png
    - assets/image/searching.png
    - assets/image/noInternet.png
    - assets/icon/createEvent.png
    - assets/icon/yourEvent.png
    - assets/image/category_country/country1.png
    - assets/image/category_country/country2.png
    - assets/image/category_country/country3.png
    - assets/image/category_country/country4.png
    - assets/image/category_country/country5.png
    - assets/image/category_country/country6.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Arial
      fonts:
        - asset: assets/font/ARLRDBD.ttf

    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 500
        - asset: assets/font/OpenSans-Light.ttf
          weight: 400

    - family: Popins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/image/CustomIcons.ttf
    - family: Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight: 600
    - family: Sofia
      fonts:
        - asset: assets/font/Sofia/SofiaProBold.otf
          weight: 900
        - asset: assets/font/Sofia/SofiaProSemiBold.otf
          weight: 800
        - asset: assets/font/Sofia/SofiaProMedium.otf
          weight: 700
        - asset: assets/font/Sofia/SofiaProRegular.otf
          weight: 600
        - asset: assets/font/Sofia/SofiaProLight.otf
          weight: 500
        - asset: assets/font/Sofia/SofiaProExtraLight.otf
          weight: 400
        - asset: assets/font/Sofia/SofiaProUltraLight.otf
          weight: 300
    - family: category
      fonts:
        - asset: assets/custom_icon/ic_category.ttf
    - family: file
      fonts:
        - asset: assets/custom_icon/ic_file.ttf
    - family: hearth
      fonts:
        - asset: assets/custom_icon/ic_hearth.ttf
    - family: home
      fonts:
        - asset: assets/custom_icon/ic_home.ttf
    - family: profile
      fonts:
        - asset: assets/custom_icon/ic_profile.ttf  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
