// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAr_SqMefyCPhilOxiMfRfaXA9IqKV7kQ',
    appId: '1:330777794222:android:92d5a9bbb51d5a1112bf3f',
    messagingSenderId: '330777794222',
    projectId: 'dikouba-test',
    databaseURL: 'https://dikouba-test.firebaseio.com',
    storageBucket: 'dikouba-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXkVvmonlYN-z6JRoZgQJD742erw8cEKc',
    appId: '1:330777794222:ios:94de446f444a438c12bf3f',
    messagingSenderId: '330777794222',
    projectId: 'dikouba-test',
    databaseURL: 'https://dikouba-test.firebaseio.com',
    storageBucket: 'dikouba-test.appspot.com',
    androidClientId: '330777794222-02h6r1rskvldign1sqvoe1lv2gs4n2u0.apps.googleusercontent.com',
    iosClientId: '330777794222-iptht1luqq03kvqko2i2hm0e4oe8fke6.apps.googleusercontent.com',
    iosBundleId: 'com.example.testIos',
  );
}
